# fly.toml para ms-gateway-unir
app = "ms-gateway-unir"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  # Apunta tu Gateway al Eureka público
  EUREKA_URL = "http://eureka-server.fly.dev:8761/eureka/"

[http_service]
  internal_port = 8762
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  # array de un solo health-check HTTP
  [[http_service.checks]]
    method      = "GET"
    path        = "/actuator/health"
    interval    = "15s"
    timeout     = "2s"
    grace_period= "60s"

[[vm]]
  memory   = "1gb"
  cpu_kind = "shared"
  cpus     = 1
